gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 6
paginate_path: blog/page:num/
permalink: /:title/

plugins: [jekyll-paginate]

authors:
  monse:
    name: Monserrat Delgadillo
    image: /assets/authors/monse.jpg
    bio:
      Estudiante en la licenciatura de Pedagogia. Siempre he buscado ayudar a los niños
      pequeños y
      a los animales, me entusiasma crear una mejor sociedad desde la raiz.
    mail: ludoteca.digital.es@gmail.com
theme: jekyll-theme-cayman
