gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  
paginate: 6
paginate_path: blog/page:num/

plugins: [jekyll-paginate]

authors:
  monse:
    name: Monserrat Delgadillo
    image: /assets/authors/monse.jpg
    bio: Lic. en Pedagogia por la UPN, originaria de Jalisco, Mexico.
theme: jekyll-theme-cayman